spring:
  application:
    name: JRoxy

proxy:
  default-load-balancing: "randomStrategy"
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      load-balancer: "randomStrategy"
      hosts:
        - address: "10.0.0.1"
          port: 9090
        - address: "10.0.0.2"
          port: 9090

server:
  port: ${proxy.listen.port}