proxy:
  default-load-balancing: "randomStrategy"
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      load-balancer: "roundRobinStrategy"
      hosts:
        - address: "127.0.0.1"
          port: 8081
        - address: "127.0.0.1"
          port: 8082
    - name: my-service-a
      domain: my-service-a.my-company.com
      load-balancer: "roundRobinStrategy"
      hosts:
        - address: "127.0.0.1"
          port: 9091