name: Java CI with Maven

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build and run tests with coverage
        run: mvn clean verify

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/

  build-image:
    name: Build Docker Image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=${VERSION}-${GIT_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t jroxy:${IMAGE_TAG} .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jroxy-image
          path: jroxy:${IMAGE_TAG} # this will save the image ID

  push-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build-image
    if: github.event_name == 'workflow_dispatch' # only manual
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and push Docker image
        run: |
          docker tag jroxy:${IMAGE_TAG} ${{ secrets.DOCKER_USERNAME }}/jroxy:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/jroxy:${IMAGE_TAG}